import type { Mail } from './types'

export const DEMO_MAILS: Mail[] = [
  {
    id: 'mail-001',
    type: 'system',
    title: 'Giriş Ödülü — 3. Gün',
    preview: 'Ardışık giriş ödülünüz hazır! 3. gün bonusunuzu talep edin.',
    body: 'Komutan, üssünüze dönüşünüzü kutluyoruz. Nebula Dominion\'a 3 gün boyunca ardışık olarak giriş yaptınız. Bu sadakat ödülünüzü talep etmeyi unutmayın — yarın sona eriyor.',
    sender: 'Nebula Sistemi',
    sentAt: '2026-05-03T10:00:00Z',
    isRead: false,
    rewards: [
      { type: 'mineral', label: 'Mineral', amount: 5000, icon: '💎' },
      { type: 'energy', label: 'Enerji', amount: 1200, icon: '⚡' },
      { type: 'gem', label: 'Kristal', amount: 50, icon: '🔮' },
    ],
    expiresAt: '2026-05-04T10:00:00Z',
  },
  {
    id: 'mail-002',
    type: 'battle_report',
    title: 'Savaş Raporu — Sektor 7-G',
    preview: 'Komutan Chen\'in kuvvetleri Sektor 7-G\'de yenilgiye uğratıldı.',
    body: 'Komutan, Sektor 7-G\'deki savunma operasyonu tamamlandı. Birimleriniz düşman kuvvetlerini geri püskürttü. Kayıplar minimal düzeyde tutuldu. Düşman hafif hasarlı birlikleri geri çekildi.',
    sender: 'Savaş İstihbarat Birimi',
    sentAt: '2026-05-03T08:30:00Z',
    isRead: false,
    rewards: [
      { type: 'mineral', label: 'Ganimet Minerali', amount: 8500, icon: '💎' },
      { type: 'energy', label: 'Ganimet Enerjisi', amount: 3200, icon: '⚡' },
    ],
  },
  {
    id: 'mail-003',
    type: 'guild',
    title: 'Lonca Rallisi — Çağrı',
    preview: 'Şef Morgath tüm üyeleri koordinasyon toplantısına çağırıyor.',
    body: 'Lonca üyeleri, Yıldız Gölü bölgesinde büyük ölçekli bir harekât planlıyoruz. Tüm aktif komutanların bu cumartesi koordinasyon toplantısına katılması bekleniyor. Strateji belirlenerek rol dağılımı yapılacak.',
    sender: 'Şef Morgath',
    sentAt: '2026-05-02T20:15:00Z',
    isRead: true,
  },
  {
    id: 'mail-004',
    type: 'system',
    title: 'Etkinlik: Nebula Fırtınası Başlıyor',
    preview: 'Haftalık Nebula Fırtınası etkinliği başladı! Özel ödüller kazanın.',
    body: 'Komutan! Bu hafta boyunca Nebula Fırtınası etkinliği aktif. Özel görevleri tamamlayarak yüksek değerli ödüller kazanabilirsiniz. Etkinlik 7 gün sürecek — kaçırmayın!',
    sender: 'Etkinlik Ekibi',
    sentAt: '2026-05-02T00:00:00Z',
    isRead: true,
    rewards: [
      { type: 'gem', label: 'Etkinlik Kristali', amount: 200, icon: '🔮' },
      { type: 'unit', label: 'Nadir Birim Parçası', amount: 3, icon: '🧬' },
    ],
    expiresAt: '2026-05-09T00:00:00Z',
  },
  {
    id: 'mail-005',
    type: 'battle_report',
    title: 'Savaş Raporu — PvP Ligi',
    preview: 'Oyuncu Vex_Thara sizi Ligi\'nde yenilgiye uğrattı.',
    body: 'Komutan, PvP Ligi maçında Vex_Thara komutasındaki Zerg kuvvetlerine karşı mağlup oldunuz. Savunma birimlerinizin konumlandırmasını gözden geçirmeniz önerilir. Lig sıralamanız 15. basamaktan 18. basamağa geriledi.',
    sender: 'PvP Lig Sistemi',
    sentAt: '2026-05-01T18:45:00Z',
    isRead: true,
  },
  {
    id: 'mail-006',
    type: 'event',
    title: 'Yeni Komutan Açıldı: Aurelius',
    preview: 'Otomat ırkı komutanı Aurelius kilidini açabilirsiniz!',
    body: 'Komutan, araştırma laboratuvarınız Aurelius\'un kilit açma koşullarını karşıladı. Otomat ırkının en gelişmiş stratejik komutanı olan Aurelius, alan kontrolü ve savunma derinliği konusunda eşsiz yeteneklere sahip.',
    sender: 'Araştırma Laboratuvarı',
    sentAt: '2026-04-30T14:20:00Z',
    isRead: true,
    rewards: [
      { type: 'item', label: 'Aurelius Kilit Parçası', amount: 1, icon: '🔓' },
    ],
  },
]
