import { Race } from '../entities/unit-type.entity';

export interface UnitTypeSeedData {
  code: string;
  name: string;
  nameTr: string;
  description: string;
  race: Race;
  ageNumber: number;
  tierLevel: number;
  globalTier: number;
  baseHp: number;
  baseAttack: number;
  baseDefense: number;
  baseSpeed: number;
  mineralCost: number;
  energyCost: number;
  populationCost: number;
  trainingTimeSeconds: number;
}

// Human Race — Age 1 (Global Tier 1–9)
// Core units: Soldier (Asker), Armored (Zırhlı), Engineer (Mühendis)
const humanAge1: UnitTypeSeedData[] = [
  {
    code: 'human_recruit',
    name: 'Recruit',
    nameTr: 'Acemi Asker',
    description: 'Basic infantry unit. Cheap and fast to train but low combat stats.',
    race: Race.HUMAN,
    ageNumber: 1,
    tierLevel: 1,
    globalTier: 1,
    baseHp: 80,
    baseAttack: 12,
    baseDefense: 5,
    baseSpeed: 6,
    mineralCost: 50,
    energyCost: 10,
    populationCost: 1,
    trainingTimeSeconds: 30,
  },
  {
    code: 'human_soldier',
    name: 'Soldier',
    nameTr: 'Asker',
    description: 'Standard infantry soldier. Balanced stats, backbone of the Human army.',
    race: Race.HUMAN,
    ageNumber: 1,
    tierLevel: 2,
    globalTier: 2,
    baseHp: 120,
    baseAttack: 20,
    baseDefense: 10,
    baseSpeed: 5,
    mineralCost: 100,
    energyCost: 20,
    populationCost: 1,
    trainingTimeSeconds: 60,
  },
  {
    code: 'human_armored',
    name: 'Armored Trooper',
    nameTr: 'Zırhlı',
    description: 'Heavy armored infantry. Excellent defense at the cost of speed.',
    race: Race.HUMAN,
    ageNumber: 1,
    tierLevel: 3,
    globalTier: 3,
    baseHp: 200,
    baseAttack: 18,
    baseDefense: 28,
    baseSpeed: 3,
    mineralCost: 150,
    energyCost: 30,
    populationCost: 2,
    trainingTimeSeconds: 90,
  },
  {
    code: 'human_engineer',
    name: 'Engineer',
    nameTr: 'Mühendis',
    description: 'Combat engineer. Provides battlefield support and structural bonuses.',
    race: Race.HUMAN,
    ageNumber: 1,
    tierLevel: 4,
    globalTier: 4,
    baseHp: 100,
    baseAttack: 15,
    baseDefense: 15,
    baseSpeed: 5,
    mineralCost: 120,
    energyCost: 40,
    populationCost: 1,
    trainingTimeSeconds: 120,
  },
  {
    code: 'human_marksman',
    name: 'Marksman',
    nameTr: 'Nişancı',
    description: 'Ranged infantry specialist. High attack, low HP.',
    race: Race.HUMAN,
    ageNumber: 1,
    tierLevel: 5,
    globalTier: 5,
    baseHp: 90,
    baseAttack: 32,
    baseDefense: 8,
    baseSpeed: 6,
    mineralCost: 180,
    energyCost: 50,
    populationCost: 1,
    trainingTimeSeconds: 150,
  },
  {
    code: 'human_scout',
    name: 'Scout',
    nameTr: 'Kaşif',
    description: 'Fast-moving recon unit. Excellent speed for flanking maneuvers.',
    race: Race.HUMAN,
    ageNumber: 1,
    tierLevel: 6,
    globalTier: 6,
    baseHp: 100,
    baseAttack: 22,
    baseDefense: 12,
    baseSpeed: 9,
    mineralCost: 160,
    energyCost: 40,
    populationCost: 1,
    trainingTimeSeconds: 120,
  },
  {
    code: 'human_heavy_trooper',
    name: 'Heavy Trooper',
    nameTr: 'Ağır Piyade',
    description: 'Elite heavy infantry. Outstanding durability and damage output.',
    race: Race.HUMAN,
    ageNumber: 1,
    tierLevel: 7,
    globalTier: 7,
    baseHp: 260,
    baseAttack: 28,
    baseDefense: 32,
    baseSpeed: 3,
    mineralCost: 220,
    energyCost: 60,
    populationCost: 2,
    trainingTimeSeconds: 180,
  },
  {
    code: 'human_sniper',
    name: 'Sniper',
    nameTr: 'Keskin Nişancı',
    description: 'Long-range precision shooter. Devastating attack, fragile in close combat.',
    race: Race.HUMAN,
    ageNumber: 1,
    tierLevel: 8,
    globalTier: 8,
    baseHp: 80,
    baseAttack: 48,
    baseDefense: 5,
    baseSpeed: 7,
    mineralCost: 300,
    energyCost: 80,
    populationCost: 1,
    trainingTimeSeconds: 240,
  },
  {
    code: 'human_commander',
    name: 'Commander',
    nameTr: 'Komutan',
    description: 'Elite field commander. Exceptional all-round stats, top of Age 1 Human tier.',
    race: Race.HUMAN,
    ageNumber: 1,
    tierLevel: 9,
    globalTier: 9,
    baseHp: 300,
    baseAttack: 38,
    baseDefense: 38,
    baseSpeed: 5,
    mineralCost: 400,
    energyCost: 100,
    populationCost: 3,
    trainingTimeSeconds: 300,
  },
];

// Zerg Race — Age 1 (Global Tier 1–9)
// Core units: Larva (Larva), Guardian (Koruyucu), Warrior (Savaşçı)
const zergAge1: UnitTypeSeedData[] = [
  {
    code: 'zerg_larva',
    name: 'Larva',
    nameTr: 'Larva',
    description: 'The most basic Zerg unit. Swarm in numbers to overwhelm enemies.',
    race: Race.ZERG,
    ageNumber: 1,
    tierLevel: 1,
    globalTier: 1,
    baseHp: 60,
    baseAttack: 8,
    baseDefense: 3,
    baseSpeed: 5,
    mineralCost: 30,
    energyCost: 5,
    populationCost: 1,
    trainingTimeSeconds: 15,
  },
  {
    code: 'zerg_zergling',
    name: 'Zergling',
    nameTr: 'Zergling',
    description: 'Fast melee attacker. Low cost, quickly produced in large numbers.',
    race: Race.ZERG,
    ageNumber: 1,
    tierLevel: 2,
    globalTier: 2,
    baseHp: 80,
    baseAttack: 16,
    baseDefense: 5,
    baseSpeed: 8,
    mineralCost: 60,
    energyCost: 10,
    populationCost: 1,
    trainingTimeSeconds: 45,
  },
  {
    code: 'zerg_guardian',
    name: 'Guardian',
    nameTr: 'Koruyucu',
    description: 'Protective Zerg tank unit. Absorbs massive damage for the swarm.',
    race: Race.ZERG,
    ageNumber: 1,
    tierLevel: 3,
    globalTier: 3,
    baseHp: 180,
    baseAttack: 14,
    baseDefense: 24,
    baseSpeed: 4,
    mineralCost: 120,
    energyCost: 25,
    populationCost: 2,
    trainingTimeSeconds: 80,
  },
  {
    code: 'zerg_warrior',
    name: 'Warrior',
    nameTr: 'Savaşçı',
    description: 'Core Zerg combat unit. Reliable attack and decent survivability.',
    race: Race.ZERG,
    ageNumber: 1,
    tierLevel: 4,
    globalTier: 4,
    baseHp: 150,
    baseAttack: 26,
    baseDefense: 15,
    baseSpeed: 6,
    mineralCost: 140,
    energyCost: 35,
    populationCost: 2,
    trainingTimeSeconds: 100,
  },
  {
    code: 'zerg_creeper',
    name: 'Creeper',
    nameTr: 'Sürünücü',
    description: 'Stealthy Zerg assault unit. Ambushes enemies with burst damage.',
    race: Race.ZERG,
    ageNumber: 1,
    tierLevel: 5,
    globalTier: 5,
    baseHp: 120,
    baseAttack: 30,
    baseDefense: 10,
    baseSpeed: 7,
    mineralCost: 160,
    energyCost: 40,
    populationCost: 1,
    trainingTimeSeconds: 120,
  },
  {
    code: 'zerg_stalker',
    name: 'Stalker',
    nameTr: 'İzleyici',
    description: 'Fast hunter unit. Relentlessly pursues weakened targets.',
    race: Race.ZERG,
    ageNumber: 1,
    tierLevel: 6,
    globalTier: 6,
    baseHp: 130,
    baseAttack: 34,
    baseDefense: 12,
    baseSpeed: 8,
    mineralCost: 200,
    energyCost: 50,
    populationCost: 2,
    trainingTimeSeconds: 150,
  },
  {
    code: 'zerg_bone_guard',
    name: 'Bone Guard',
    nameTr: 'Kemik Muhafızı',
    description: 'Armored Zerg defender. Bone-plated exoskeleton provides extreme durability.',
    race: Race.ZERG,
    ageNumber: 1,
    tierLevel: 7,
    globalTier: 7,
    baseHp: 220,
    baseAttack: 28,
    baseDefense: 30,
    baseSpeed: 4,
    mineralCost: 250,
    energyCost: 65,
    populationCost: 3,
    trainingTimeSeconds: 180,
  },
  {
    code: 'zerg_spore_drone',
    name: 'Spore Drone',
    nameTr: 'Spor Dron',
    description: 'Ranged Zerg attacker. Launches acidic spores over long distances.',
    race: Race.ZERG,
    ageNumber: 1,
    tierLevel: 8,
    globalTier: 8,
    baseHp: 100,
    baseAttack: 42,
    baseDefense: 8,
    baseSpeed: 9,
    mineralCost: 280,
    energyCost: 75,
    populationCost: 1,
    trainingTimeSeconds: 210,
  },
  {
    code: 'zerg_hive_lord',
    name: 'Hive Lord',
    nameTr: 'Kovan Lordu',
    description: 'Apex Zerg predator. Commands lesser units and deals catastrophic damage.',
    race: Race.ZERG,
    ageNumber: 1,
    tierLevel: 9,
    globalTier: 9,
    baseHp: 350,
    baseAttack: 42,
    baseDefense: 34,
    baseSpeed: 5,
    mineralCost: 380,
    energyCost: 95,
    populationCost: 3,
    trainingTimeSeconds: 280,
  },
];

export const AGE_1_UNIT_TYPES: UnitTypeSeedData[] = [...humanAge1, ...zergAge1];
