export const CHARACTER_ASSETS = {
  zerg: {
    vex_thara: '/assets/characters/zerg/vex_thara.png',
    morgath: '/assets/characters/zerg/morgath.png',
    threnix: '/assets/characters/zerg/threnix.png',
  },
  otomat: {
    demiurge_prime: '/assets/characters/otomat/demiurge_prime.png',
    aurelius: '/assets/characters/otomat/aurelius.png',
    crucible: '/assets/characters/otomat/crucible.png',
  },
  canavar: {
    khorvash: '/assets/characters/canavar/khorvash.png',
    ravenna: '/assets/characters/canavar/ravenna.png',
    ulrek: '/assets/characters/canavar/ulrek.png',
  },
  insan: {
    voss: '/assets/characters/insan/voss.png',
    chen: '/assets/characters/insan/chen.png',
    reyes: '/assets/characters/insan/reyes.png',
    kovacs: '/assets/characters/insan/kovacs.png',
  },
  seytan: {
    malphas: '/assets/characters/seytan/malphas.png',
    lilithra: '/assets/characters/seytan/lilithra.png',
    vorhaal: '/assets/characters/seytan/vorhaal.png',
    azurath: '/assets/characters/seytan/azurath.png',
  },
} as const;

/**
 * Unit portraits — 6 per race, 30 total. Generated by
 * `scripts/comfy-sweep.mjs units` (Lightning XL @ 512²) and saved under
 * `apps/web/public/assets/units/<race>/<slug>.png`.
 *
 * Slug convention: matches what `slug()` in formation-api.ts produces
 * from the FE display name (nd-tokens.ts RACES[*].units[].n) — Turkish
 * diacritics folded (ş→s, ğ→g, ç→c, ö→o, ü→u, ı→i), spaces → underscores.
 * That way unitToSlotUnit(BackendUnit) keeps using the same portraitFor()
 * lookup and just falls into UNIT_ASSETS first instead of cascading to
 * a commander portrait fallback.
 *
 * Where the BE UnitType enum already has a row (insan + zerg in
 * apps/game-server/src/units/constants/race-configs.constants.ts), the
 * BE `type` field — title-cased on the wire by formation-api.ts — also
 * slugs to one of these keys. So `siege_tank` (not in the FE-only lex)
 * isn't covered yet — TODO when the merge-ladder + train catalog
 * unifies across the 3 unwired races (otomat/canavar/seytan).
 */
export const UNIT_ASSETS = {
  insan: {
    marine:           '/assets/units/insan/marine.png',
    // Medic + Siege Tank + Ghost — BE-only trainable units (not in the
    // FE merge-ladder lex but they show up on the formation roster
    // and /merge cards once a player trains them).
    medic:            '/assets/units/insan/medic.png',
    siege_tank:       '/assets/units/insan/siege_tank.png',
    ghost:            '/assets/units/insan/ghost.png',
    sniper:           '/assets/units/insan/sniper.png',
    engineer:         '/assets/units/insan/engineer.png',
    mecha_walker:     '/assets/units/insan/mecha_walker.png',
    genetic_warrior:  '/assets/units/insan/genetic_warrior.png',
    captain:          '/assets/units/insan/captain.png',
  },
  zerg: {
    larva:            '/assets/units/zerg/larva.png',
    penceli_avci:     '/assets/units/zerg/penceli_avci.png',
    tuneli_yutan:     '/assets/units/zerg/tuneli_yutan.png',
    mutasyon_lord:    '/assets/units/zerg/mutasyon_lord.png',
    mega_lokost:      '/assets/units/zerg/mega_lokost.png',
    beyin_kurt:       '/assets/units/zerg/beyin_kurt.png',
  },
  otomat: {
    sentinel:         '/assets/units/otomat/sentinel.png',
    drone_operator:   '/assets/units/otomat/drone_operator.png',
    cataphract:       '/assets/units/otomat/cataphract.png',
    phoenix_komutan:  '/assets/units/otomat/phoenix_komutan.png',
    yargi_cekirdek:   '/assets/units/otomat/yargi_cekirdek.png',
    demiurge_birimi:  '/assets/units/otomat/demiurge_birimi.png',
  },
  canavar: {
    howler:           '/assets/units/canavar/howler.png',
    yelmik_avci:      '/assets/units/canavar/yelmik_avci.png',
    firtina_bogasi:   '/assets/units/canavar/firtina_bogasi.png',
    ejder_aslani:     '/assets/units/canavar/ejder_aslani.png',
    atavar_ruhu:      '/assets/units/canavar/atavar_ruhu.png',
    beast_god_yavru:  '/assets/units/canavar/beast_god_yavru.png',
  },
  seytan: {
    imp:              '/assets/units/seytan/imp.png',
    cadi_kalfasi:     '/assets/units/seytan/cadi_kalfasi.png',
    lanetli_asker:    '/assets/units/seytan/lanetli_asker.png',
    kanli_lord:       '/assets/units/seytan/kanli_lord.png',
    kanat_seytani:    '/assets/units/seytan/kanat_seytani.png',
    demon_lord:       '/assets/units/seytan/demon_lord.png',
  },
} as const;

export const STRUCTURE_ASSETS = {
  atalar_magarasi: '/assets/structures/atalar_magarasi.png',
  karanlik_mahkeme: '/assets/structures/karanlik_mahkeme.png',
  kovan_kalbi: '/assets/structures/kovan_kalbi.png',
  lanet_tapinagi: '/assets/structures/lanet_tapinagi.png',
  mutasyon_cukuru: '/assets/structures/mutasyon_cukuru.png',
  sonsuzluk_cekirdegi: '/assets/structures/sonsuzluk_cekirdegi.png',
  yutucu_tumsegi: '/assets/structures/yutucu_tumsegi.png',
  yutucu_yildiz_akademisi: '/assets/structures/yutucu_yildiz_akademisi.png',
} as const;

export type RaceAssetKey = keyof typeof CHARACTER_ASSETS;
export type StructureAssetKey = keyof typeof STRUCTURE_ASSETS;
