/**
 * Client-side gate hook + types.
 *
 * Pairs with backend's GET /api/progression/gates endpoint. The backend is
 * the source-of-truth for whether a button is unlocked + the exact current vs.
 * required values; the frontend just renders the result.
 *
 * Hybrid SoT: the *rule list* (which gates exist, which requirements they
 * have) lives in backend gates.config.ts. The *display copy* (Turkish names,
 * inline subtitle) is generated by backend describeRule(). The hook caches
 * the response and shares it via a tiny store so every <GatedButton> on the
 * page hits the API at most once per render cycle.
 */

import { useEffect, useSyncExternalStore } from 'react';
import { getAccessToken, hasSession } from './session';

// Mirror game-server-api's URL resolution since it doesn't export the base
// constant. Pattern matches `apps/web/src/lib/game-server-api.ts:RAW`.
const GAME_SERVER_BASE = process.env.NEXT_PUBLIC_GAME_SERVER_URL ?? 'http://localhost:3001';

export type RuleType =
  | 'always_on'
  | 'level'
  | 'age'
  | 'building'
  | 'unit'
  | 'resource'
  | 'race';

export interface ResolvedRequirement {
  type: RuleType;
  short: string;
  long: string;
  current: string;
  required: string;
  met: boolean;
  severity: 'hard' | 'soft';
}

export interface GateEvalResult {
  unlocked: boolean;
  requirements: ResolvedRequirement[];
  primaryHint: string | null;
}

export type GateMap = Record<string, GateEvalResult>;

// ── In-memory cache (one map per app session) ───────────────────────────────

let sData: GateMap | null = null;
let sError: string | null = null;
let sLoading = false;
let sInflight: Promise<void> | null = null;
const sListeners = new Set<() => void>();

function notify() { for (const l of sListeners) l(); }

async function fetchGates(): Promise<void> {
  if (!hasSession()) {
    sData = null;
    sLoading = false;
    sError = null;
    notify();
    return;
  }
  const token = getAccessToken();
  if (!token) return;
  sLoading = true;
  notify();
  try {
    const res = await fetch(`${GAME_SERVER_BASE}/api/gates`, {
      headers: { Authorization: `Bearer ${token}` },
    });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    sData = (await res.json()) as GateMap;
    sError = null;
  } catch (err) {
    sError = err instanceof Error ? err.message : String(err);
  } finally {
    sLoading = false;
    sInflight = null;
    notify();
  }
}

/**
 * Subscribe to the gate map. Triggers a single fetch on first mount; consumers
 * can call `refreshGates()` after any action that may have unlocked something
 * (built a building, levelled up, picked a race, etc.).
 */
export function useGates(): { data: GateMap | null; loading: boolean; error: string | null } {
  const subscribe = (cb: () => void) => {
    sListeners.add(cb);
    return () => { sListeners.delete(cb); };
  };
  useEffect(() => {
    if (sData === null && !sLoading && sInflight === null) {
      sInflight = fetchGates();
    }
  }, []);
  return useSyncExternalStore(
    subscribe,
    () => ({ data: sData, loading: sLoading, error: sError }),
    () => ({ data: null, loading: true, error: null }),
  );
}

/** Lookup a single gate's result. Returns null until first fetch completes. */
export function useGate(gateId: string): GateEvalResult | null {
  const { data } = useGates();
  return data?.[gateId] ?? null;
}

/** Force a refetch — call after any state-changing user action. */
export function refreshGates(): void {
  if (sInflight) return;   // dedupe simultaneous requests
  sInflight = fetchGates();
}

/**
 * Optimistic check used by <GatedButton>: while the gate map is loading we
 * render the button as enabled (so first-paint doesn't disable buttons that
 * are actually open). Once data arrives, the real state takes over.
 */
export function gateAllows(gate: GateEvalResult | null): boolean {
  return gate === null || gate.unlocked;
}
